// Mocks generated by Mockito 5.4.4 from annotations
// in gerenciador_pedidos/test/clientes_mock_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gerenciador_pedidos/models/cliente.dart' as _i2;
import 'package:gerenciador_pedidos/services/clientes_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCliente_0 extends _i1.SmartFake implements _i2.Cliente {
  _FakeCliente_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ClientesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientesService extends _i1.Mock implements _i3.ClientesService {
  MockClientesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Cliente>> findAll() => (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Cliente>>.value(<_i2.Cliente>[]),
      ) as _i4.Future<List<_i2.Cliente>>);

  @override
  _i4.Future<String> create(_i2.Cliente? cliente) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [cliente],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #create,
            [cliente],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<_i2.Cliente> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Cliente>.value(_FakeCliente_0(
          this,
          Invocation.method(
            #findById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Cliente>);
}
